---
title: "Code Red: Unpacking Inequality"
output: 
  html_document:
    toc: true
    toc_float: true
---

## SNAP enrollment data:

The SNAP enrollment data was acquired from the American Community Survey 5-year estimates of 2022 from the Census Bureau. The original dataset contained estimates for SNAP/Food stamp enrollment at the census tract level as well as other households attributes at the census tract level: estimate and percent for distribution of race and ethnicity, poverty status, disability status, presentation of children under age of 18, etc.

We selected the variables that were relevant to our analysis to build the final dataset, the final variables included were the following:
  
  - ` r geoid`: the geographic id for identification of census tract 
  - `total_ct_households`: estimate total count for number of households 
  - `ph_with_children`: estimate percentage of households with children under 18 years
  - `ph_no_children`: estimate percentage of households without children under 18 years 
  - `ph_below_poverty`:estimate percentage of households below poverty level in the past 12 months
  - `ph_above_poverty`: estimate percentage of households at or above poverty level in the past 12 months
  - `ph_disability`: estimate percentage of households with one or more people with disability 
  - `ph_no_disability`: estimate percentage of households with no person with disability 
  - `ph_white`: estimate percent households race and Hispanic or Latino origin of householder, White alone
  - `ph_black`: estimate percent households race and Hispanic or Latino origin of householder, Black or African American alone
  - `ph_asian`: estimate percent households race and Hispanic or Latino origin of householder, Asian alone
  - `ph_other race`: estimate percent households race and Hispanic or Latino origin of householder, other races (derived from the estimate value for White, Black and Asian race groups)
  - `ph_hispanic`: estimate percent households race and Hispanic or Latino origin of householder, Hispanic or Latino origin of any race
  - `ph_non_hispanic`: estimate percent households race and Hispanic or Latino origin of householder, not of Hispanic or Latino origin of any race  (derived from the estimate value for Hispanic or Latino origin of any race)
  - `ph_no_work`:estimate percent of families with no workers in past 12 months 
  - `ph_1_work`: estimate percent of families with 1 worker in past 12 months 
  - `ph_2_work`: estimate percent of families with 2 or more workers in past 12 months 
  - `ph_snap`: estimate percent of households receiving SNAP/Food Stamp 

## Historic Redlining Score Data

The historic redlining score(HRS) (`hrs2020`) was obtained from the calculation by the National Community Reinvestment Coalition(NCRC). It was a weighted score calculated based on the percentage of the area within each 2020 census tract according to HOLC grades. HRS ranged from 1-4, the higher the score indicated a greater level of historical redlining. The detailed method for calculating the HRS was indicated in the figure below. The hrs data was divided into quartiles and the division of quartiles is indicated by the `interval2020` variable. The more detailed methodology regarding coding for redlining grades can be found [here](https://ncrc.org/holc-health/#methods).

We filtered based on the geoid to only keep the data for the census tracts within NYC based on the fipcodes for NYC counties. We recoded the census tracts with HOLC grades according to hrs. A (hrs: 1~1.5) defined as "Best", B (hrs: 1.5~2.5) defined as "Still Desirable", C (hrs: 2.5~3.5) defined as "Definitely Declining” and D(hrs > 3.5) defined as "Hazardous”.

## Recognized Healthy Store in NYC 

We obtained a data regarding recognized healthy store from the NYC Department of Health and Mental Hygiene. This dataset contained 675 bodegas & grocery stores receiving recognition from Borough President's Office regarding providing healthy food choices to its customers. The original dataset contained variables describing basic information of the stores(`name`,`store identifier`), geographic location(`address`, `census tract`, `zip code`, `borough`, `longitude` and `latitude`), year awarded and the program wave. 

## PLACE data 

We also extracted the PLACES: Local Data for Better Health, 2024 release for NYC census tracts from CDC to obtain the prevalence of a variety of health indicators that are likely associated with food insecurity: `diabetes`, `obesity` and `high cholesterol`. 
