---
title: "Team Registration and Project Proposal"
date: "2024-11-07"
output: github_document
---

**Group members (name and uni)**: Pradeeti Mainali (pm3260), Sining Leng (sl5454), Polly Wu (rw3031), Shizhe Zhang (sz3214), Yan Li (yl5505)

**Tentative Project Title**:  Code Red: Unpacking Inequality

**Motivation for this project**: This project aims to understand and uncover how historical redlining policies can contribute to modern poverty-level disparities and healthy food access. By identifying these disparities, the exploration can provide actionable insights for policymakers and community organizations aiming to address food deserts and improve the quality of life in underserved areas.

**Intended final products**: Website describing the data set and our regression results, a screencast of our website, and a written report that details how we completed our project.

**Anticipated data sources**: 

- [Historical Redlining Scores](https://www.openicpsr.org/openicpsr/project/141121/version/V2/view) 
- [NYC recognized healthy stores](https://data.cityofnewyork.us/Health/Recognized-Shop-Healthy-Stores/ud4g-9x9z/about_data)
- [American Community Survey](https://www.census.gov/programs-surveys/acs)

**Planned analyses/visualizations/coding challenges:**

- *Planned Analyses*:
  - Regression models to assess the relationship between redlining score and current outcomes (e.g., income, health, housing prices), adjust for potential confounders. 
  - A descriptive comparison of social and demographic characteristics between A-grade and D-grade neighborhoods.
  - Key metrics: race and ethnicity distribution, poverty level, median income, and education levels.
- *Visualizations*: Geospatial visualization of historical redlining grades overlaid with the distribution of healthy food stores in NYC.
- *Coding challenges*: We have several data sets that need to be cleaned and merged. Matching the census data with the NYC healthy food store data (need to match census tract with zip codes)

**Planned timeline**:

- November 8th: Submit the Proposal [Completed]
- November 11-15: Project review meeting (Topic Change) [Completed]
- Nov 24: Finalizing plans and starting work (Internal deadline) [Completed]
- Nov 29: Webpage work due (internal deadline)
- Dec 3: Screen cast recorded and report written (internal deadline). The final review of work starts.
- December 7: Report, webpage, and screen cast, peer assessment due.
- December 12th: In-class discussion of projects

